AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::Serverless-2016-10-31
  - AWS::LanguageExtensions
Mappings:
  awsAccounts:
    111111111111:
      stage: local
Conditions:
  isProductionAccount: !Equals
    - !FindInMap
      - awsAccounts
      - !Ref 'AWS::AccountId'
      - stage
    - prod
Globals:
  Function:
    Timeout: !Ref Timeout
    Tracing: Active
    Architectures:
      - arm64
    Runtime: nodejs18.x
    MemorySize: 128
    PropagateTags: true
  Api:
    TracingEnabled: true
Metadata:
  expand:
    plugins:
      - '../../src/plugins/esbuild-node.js'
      - '../../src/plugins/run-script-hooks.js'
    config:
      esbuild:
        config: ./esbuild-config.yaml
      script:
        hooks:
          pre:build:
            - command: 'echo'
              args:
                - value: 'pre build!'
          post:build:
            - command: 'echo'
              args:
                - value: 'post build!'

Description: |
  hello
  Sample SAM Template for hello

Resources:
  HelloWorldFunction:
    Condition: isProductionAccount
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get

Parameters:
  Timeout:
    Type: Number
    Description: Default timeout

Rules:
  ValidateTimeout:
    Assertions:
      - Assert: !Not [!Equals [!Ref Timeout, 0]]
        AssertDescription: "Timeout must not be 0."

Outputs:
  HelloWorldApi:
    Condition: isProductionAccount
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value: !Sub >-
      https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/
  HelloWorldFunction:
    Condition: isProductionAccount
    Description: Hello World Lambda Function ARN
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Condition: isProductionAccount
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt HelloWorldFunctionRole.Arn
