env:
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended-type-checked
  - plugin:unicorn/recommended
parserOptions:
  project: ./tsconfig.eslint.json
  parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
rules:
  '@typescript-eslint/no-unsafe-assignment': 'off'
  '@typescript-eslint/no-unsafe-call': 'off'
  '@typescript-eslint/no-unsafe-member-access': 'off'
  '@typescript-eslint/no-unsafe-return': 'off'
  '@typescript-eslint/no-unsafe-argument': 'off'
  'unicorn/prevent-abbreviations': 'off'
