AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Timeout: !Ref Timeout
    Tracing: Active
    Architectures:
      - arm64
    Runtime: nodejs18.x
    MemorySize: 128
    PropagateTags: true
  Api:
    TracingEnabled: true
Metadata:
  plugins:
    - '@starterstack/sam-expand/plugins/esbuild-node'
  custom:
    esbuild:
      config: ./esbuild-config.yaml

Description: |
  hello
  Sample SAM Template for hello

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get

Parameters:
  Timeout:
    Type: Number
    Description: Default timeout

Outputs:
  HelloWorldApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value: !Sub >-
      https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/
  HelloWorldFunction:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt HelloWorldFunctionRole.Arn
