name: ci

on:
  push:
    branches:
      - main
  pull_request:
    types: [assigned, opened, synchronize, reopened, labeled]
  workflow_dispatch:

jobs:
  test:
    uses: 'starterstack/sam-expand/.github/workflows/test.yml@main'
