name: test

on:
  workflow_call:

jobs:
  unit-tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.3.0
        with:
          node-version: 22
          cache: npm
      - name: npm install
        run: npm ci --ignore-scripts
      - name: build
        run: npm run build
      - name: typedoc
        run: npm run typedoc
      - name: run tests
        run: npm t
