name: test

on:
  workflow_call:

jobs:
  unit-tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.0.0
        with:
          node-version: 20
          cache: npm
      - name: npm install
        run: |
          npm install \
            --no-save \
            --audit false \
            --fund false \
            --loglevel=error \
            --ignore-scripts
      - name: run tests
        run: |
          npm t
